<?php
/**
 * @author Vectra Team
 * @copyright Copyright © Vectra Business Technologies
 * @package Vectra_MiniCartSlider
 *
 * @var block Vectra\MiniCartSlider\Block\Html\EmptyCartCMSBlock
 */

$blockData = $this->getMiniCartBlockData();
?>

<?php if($this->isMiniCartSliderEnabled() && $blockData['enabled']): ?>
    <div class="minicartCms" style="display: none;">
        <?= $this->getCmsHtml($blockData['contentId']); ?>
    </div>
<?php endif; ?>

<?php if($this->isMiniCartSliderEnabled()): ?>
    <script type="text/javascript">
        require([
            'jquery'
        ], function ($) {
            'use strict';

            $(document).ready(function () {
                $('body').addClass('vectra-minicartSlider');
            })

        });
    </script>
    <div class="slider-modals-wrapper"></div>
<?php endif; ?> 

