<?php
/**
 * @author Vectra Team
 * @copyright Copyright © Vectra Business Technologies
 * @package Vectra_MiniCartSlider
 * 
*/

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php $isMiniCartSliderEnabled = $block->isMiniCartSliderEnabled() ?>

<div data-block="minicart" class="minicart-wrapper">
    <a class="<?= ($isMiniCartSliderEnabled) ? 'triggerCartSlider': 'triggerDefaultCart' ?> action showcart" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
       data-bind="scope: 'minicart_content'">
        <span class="text"><?= $block->escapeHtml(__('My Cart')) ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false && !isLoading() },
               blockLoader: isLoading">
            <span class="counter-number">
                <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count').toLocaleString(window.LOCALE) --><!-- /ko -->
                <!-- /ko -->
            </span>
            <span class="counter-label">
            <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count').toLocaleString(window.LOCALE) --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
            <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()):?>
        <?php if (!$isMiniCartSliderEnabled): ?>
            <div class="block block-minicart"
                data-role="dropdownDialog"
                data-mage-init='{"dropdownDialog":{
                    "appendTo":"[data-block=minicart]",
                    "triggerTarget":".triggerDefaultCart",
                    "timeout": "2000",
                    "closeOnMouseLeave": false,
                    "closeOnEscape": true,
                    "triggerClass":"active",
                    "parentClass":"active",
                    "buttons":[]}}'>
                <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
                <?= $block->getChildHtml('minicart.addons') ?>
            </div>
        <?php endif; ?>

        <?php if ($isMiniCartSliderEnabled): ?>
            <div data-bind="mageInit: {
                    'Magento_Ui/js/modal/modal':{
                        'appendTo':'[data-block=minicart]',
                        'type': 'slide',
                        'trigger': '.triggerCartSlider',
                        'responsive': true,
                        'timeout': '2000',
                        'closeOnMouseLeave': false,
                        'closeOnEscape': true,
                        'triggerClass':'active',
                        'parentClass': 'active',
                        'parentModalClass': 'vectra-minicartSlider active',
                        'buttons':[]}}">
                <div class="block block-minicart vectra-minicart">
                    <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                        <!-- ko template: getTemplate() --><!-- /ko -->
                        <!-- ko ifnot: getCartParam('summary_count') -->
                            <div class="emptyCartBlock">
                                <?= $this->getLayout()->createBlock("Vectra\MiniCartSlider\Block\Html\EmptyCartCMSBlock")->setTemplate("Vectra_MiniCartSlider::cart/minicart-cms.phtml")->toHtml(); ?>
                            </div>
                        <!-- /ko -->
                    </div>
                </div>
            </div>
        <?php endif; ?>

    <?php else: ?>
        <?php $scriptString = <<<script
            require(['jquery'], function ($) {
                $('a.action.showcart').on('click', function() {
                    $(document.body).trigger('processStart');
                });
            });
script;
        ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
    <?php endif ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], 'window.checkout = ' .
     /* @noEscape */ $block->getSerializedConfig(), false); ?>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
                $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
            ) ?>"
        }
    }
    </script>
</div>